CREATE TABLE HTA.SCHOOL_DEPARTMENTS
(
	-- 학과코드
	DEPT_CODE CHAR(4) NOT NULL,
	-- 학과이름
	DEPT_NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT DEPT_CODE_PK PRIMARY KEY (DEPT_CODE)
);


CREATE TABLE HTA.SCHOOL_EXAMS
(
    -- 시험성적 번호
	EXAM_NO NUMBER(6) NOT NULL,
	-- 수강신청등록번호
	REGISTRATION_NO NUMBER(6) NOT NULL,
	-- 시험종류(중간고사, 기말고사)
	EXAM_TYPE VARCHAR2(50),
	-- 시험성적(0~100)
	EXAM_SCORE NUMBER(3,0),
	-- 성적 등록일
	EXAM_CREATE_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (EXAM_NO)
);


CREATE TABLE HTA.SCHOOL_LECTURES
(
	-- 강의번호
	LECTURE_NO NUMBER(6) NOT NULL,
	-- 강의명
	LECTURE_NAME VARCHAR2(200) NOT NULL,
	-- 개설년도
	LECTURE_YEAR NUMBER(4,0) NOT NULL,
	-- 개설학기(1:1학기, 2:2학기, 3:계절학기)
	LECTURE_TERM NUMBER(1),
	-- 강의종류(11:교양선택, 2:교양필수, 3:전공선택, 4:전공필수)
	LECTURE_TYPE NUMBER(1),
	-- 수강대상학년
	LECTURE_GRADE NUMBER(1),
	-- 신청정원
	LECTURE_QUOTA NUMBER(3,0) NOT NULL,
	-- 신청자수
	LECTURE_REG_CNT NUMBER(3,0) DEFAULT 0,
	-- 폐강여부
	LECTURE_CLOSED CHAR(1) DEFAULT '''N''',
	-- 모집마감여부
	LECTURE_COMPLETED CHAR(1) DEFAULT '''N''',
	-- 강의개설 교수코드
	PROF_CODE CHAR(4),
	-- 개설학과 코드
	DEPT_CODE CHAR(4),
	-- 강의 등록일
	LECTURE_CREATE_DATE DATE DEFAULT SYSDATE	
,
	CONSTRAINT LECTURE_NO_PK PRIMARY KEY (LECTURE_NO)
);


CREATE TABLE HTA.SCHOOL_LECTURES_REGISTRATIONS
(
	-- 수강신청등록번호
	REGISTRATION_NO NUMBER(6) NOT NULL,
	-- 학생번호
	STUDENT_NO NUMBER(6) NOT NULL,
	-- 강의번호
	LECTURE_NO NUMBER(6) NOT NULL,
	-- 수강신청등록일
	REGISTRATION_CREATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT REGISTRATION_NO_PK PRIMARY KEY (REGISTRATION_NO)
);


CREATE TABLE HTA.SCHOOL_PROFESSORS
(
	-- 교수코드
	PROF_CODE CHAR(4) NOT NULL,
	-- 교수이름
	PROF_NAME VARCHAR2(100) NOT NULL,
	-- 교수직위(시간강사, 전임강사, 조교수, 부교수, 정교수)
	PROF_POSITION VARCHAR2(20) NOT NULL,
	-- 학과코드
	DEPT_CODE CHAR(4) NOT NULL,
	-- 교수 등록일
	PROF_CREATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT PROF_CODE_PK PRIMARY KEY (PROF_CODE)
);


CREATE TABLE HTA.SCHOOL_STUDENTS
(
	-- 학생번호
	STUDENT_NO NUMBER(6) NOT NULL,
	-- 학생이름
	STUDENT_NAME VARCHAR2(100) NOT NULL,
	-- 이메일
	STUDENT_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
	-- 학년
	STUDENT_GRADE NUMBER(1),
	-- 소속학과코드
	DEPT_CODE CHAR(4),
	-- 학생 등록일
	STUDENT_CREATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT STUDENT_NO_PK PRIMARY KEY (STUDENT_NO)
);



ALTER TABLE HTA.SCHOOL_LECTURES
	ADD CONSTRAINT LECTURE_DEPT_CODE_FK FOREIGN KEY (DEPT_CODE)
	REFERENCES HTA.SCHOOL_DEPARTMENTS (DEPT_CODE)
;


ALTER TABLE HTA.SCHOOL_PROFESSORS
	ADD CONSTRAINT PROF_DEPT_CODE_FK FOREIGN KEY (DEPT_CODE)
	REFERENCES HTA.SCHOOL_DEPARTMENTS (DEPT_CODE)
;


ALTER TABLE HTA.SCHOOL_STUDENTS
	ADD CONSTRAINT STUDENT_DEPT_CODE_FK FOREIGN KEY (DEPT_CODE)
	REFERENCES HTA.SCHOOL_DEPARTMENTS (DEPT_CODE)
;


ALTER TABLE HTA.SCHOOL_LECTURES_REGISTRATIONS
	ADD CONSTRAINT REGISTRATION_LECTURE_NO_FK FOREIGN KEY (LECTURE_NO)
	REFERENCES HTA.SCHOOL_LECTURES (LECTURE_NO)
;


ALTER TABLE HTA.SCHOOL_EXAMS
	ADD CONSTRAINT EXAMS_REGISTRAION_NO_FK FOREIGN KEY (REGISTRATION_NO)
	REFERENCES HTA.SCHOOL_LECTURES_REGISTRATIONS (REGISTRATION_NO)
;


ALTER TABLE HTA.SCHOOL_LECTURES
	ADD CONSTRAINT LECTURE_PROF_CODE_FK FOREIGN KEY (PROF_CODE)
	REFERENCES HTA.SCHOOL_PROFESSORS (PROF_CODE)
;


ALTER TABLE HTA.SCHOOL_LECTURES_REGISTRATIONS
	ADD CONSTRAINT REGISTRATION_STUDENT_NO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES HTA.SCHOOL_STUDENTS (STUDENT_NO)
;


COMMENT ON COLUMN HTA.SCHOOL_DEPARTMENTS.DEPT_CODE IS '학과코드';
COMMENT ON COLUMN HTA.SCHOOL_DEPARTMENTS.DEPT_NAME IS '학과이름';
COMMENT ON COLUMN HTA.SCHOOL_EXAMS.EXAM_NO IS '시험성적번호';
COMMENT ON COLUMN HTA.SCHOOL_EXAMS.REGISTRATION_NO IS '수강신청등록번호';
COMMENT ON COLUMN HTA.SCHOOL_EXAMS.EXAM_TYPE IS '시험종류(중간고사, 기말고사)';
COMMENT ON COLUMN HTA.SCHOOL_EXAMS.EXAM_SCORE IS '시험성적(0~100)';
COMMENT ON COLUMN HTA.SCHOOL_EXAMS.EXAM_CREATE_DATE IS '성적 등록일';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_NO IS '강의번호';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_NAME IS '강의명';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_YEAR IS '개설년도';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_TERM IS '개설학기(1:1학기, 2:2학기, 3:계절학기)';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_TYPE IS '강의종류(11:교양선택, 2:교양필수, 3:전공선택, 4:전공필수)';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_GRADE IS '수강대상학년';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_QUOTA IS '신청정원';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_REG_CNT IS '신청자수';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_CLOSED IS '폐강여부';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_COMPLETED IS '모집마감여부';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.PROF_CODE IS '강의개설 교수코드';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.DEPT_CODE IS '개설학과 코드';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES.LECTURE_CREATE_DATE IS '강의 등록일';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES_REGISTRATIONS.REGISTRATION_NO IS '수강신청등록번호';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES_REGISTRATIONS.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES_REGISTRATIONS.LECTURE_NO IS '강의번호';
COMMENT ON COLUMN HTA.SCHOOL_LECTURES_REGISTRATIONS.REGISTRATION_CREATE_DATE IS '수강신청등록일';
COMMENT ON COLUMN HTA.SCHOOL_PROFESSORS.PROF_CODE IS '교수코드';
COMMENT ON COLUMN HTA.SCHOOL_PROFESSORS.PROF_NAME IS '교수이름';
COMMENT ON COLUMN HTA.SCHOOL_PROFESSORS.PROF_POSITION IS '교수직위(시간강사, 전임강사, 조교수, 부교수, 정교수)';
COMMENT ON COLUMN HTA.SCHOOL_PROFESSORS.DEPT_CODE IS '학과코드';
COMMENT ON COLUMN HTA.SCHOOL_PROFESSORS.PROF_CREATE_DATE IS '교수 등록일';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.STUDENT_NAME IS '학생이름';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.STUDENT_EMAIL IS '이메일';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.STUDENT_GRADE IS '학년';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.DEPT_CODE IS '소속학과코드';
COMMENT ON COLUMN HTA.SCHOOL_STUDENTS.STUDENT_CREATE_DATE IS '학생 등록일';

CREATE SEQUENCE SCHOOL_STUDENT_SEQ;
CREATE SEQUENCE SCHOOL_LECTURE_SEQ;
CREATE SEQUENCE SCHOOL_REGISTRATION_SEQ;
CREATE SEQUENCE SCHOOL_EXAM_SEQ;



