INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'java', 'Java');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'c', 'C, C++');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'python', '파이썬');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'db', '빅데이터');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'data', '데이터분석');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'ml', '머신러닝');
INSERT INTO APPLICANT_SKILLS (ID, SKILL_NAME, SKILL_LABEL) VALUES (NULL, 'ai', '인공지능');

INSERT INTO APPLICANTS(ID, NAME, EMAIL, AGREEMENT, CAREER, DESCRIPTION, CREATED_DATE)
VALUES(NULL, '김유신', 'kim@gmail.com', false, 5, '다양한 플랫폼에서 개발이 가능합니다.', CURRENT_DATE);
INSERT INTO APPLICANTS(ID, NAME, EMAIL, AGREEMENT, CAREER, DESCRIPTION, CREATED_DATE)
VALUES(NULL, '강감찬', 'KANG@naver.com', true, 3, '스프링 기반의 웹 애플리케이션 개발이 가능합니다.', CURRENT_DATE);
INSERT INTO APPLICANTS(ID, NAME, EMAIL, AGREEMENT, CAREER, DESCRIPTION, CREATED_DATE)
VALUES(NULL, '이순신', 'leesooshin@hanmail.net', false, 0, '초급개발자 입니다.', CURRENT_DATE);

INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 1, 1, CURRENT_DATE);
INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 1, 2, CURRENT_DATE);
INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 1, 3, CURRENT_DATE);
INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 1, 4, CURRENT_DATE);

INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 2, 1, CURRENT_DATE);
INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 2, 4, CURRENT_DATE);

INSERT INTO APPLICANT_HOLDING_SKILLS(ID, APP_ID, SKILL_ID, CREATED_DATE)
VALUES(NULL, 3, 1, CURRENT_DATE);




commit;