CREATE TABLE IF NOT EXISTS APPLICANTS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    AGREEMENT BOOLEAN DEFAULT TRUE,
    CAREER int default 0,
    DESCRIPTION TEXT,
    CREATED_DATE date,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS APPLICANT_SKILLS (
  ID int not null AUTO_INCREMENT,
  SKILL_name varchar(128) not null,
  SKILL_label varchar(128) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS APPLICANT_HOLDING_SKILLS (
  ID INT  NOT NULL AUTO_INCREMENT,
  APP_ID INT NOT NULL,
  SKILL_ID int not null,
  CREATED_DATE DATE,
  PRIMARY KEY (ID)
);

